### ISSUE TITLE
[Week 3] Project Milestone: Inception

### ISSUE THREAD

**Issue by JonathanLeeWH** [cs2103-ay1819s2-t12-3/main#2]
## Decide on an overall project direction (user profile, problem addressed, optimize or morph?).

- [ ] Set up a weekly project meeting time/venue with your team members

We recommend at least one face-to-face project meeting per week. The project meeting time can be used to discuss project related things, but also, can be used as a time for team members to work on the project tasks individually (having all members in the same place will facilitate easier collaboration and more peer-learning).

- [ ] Play around with AB4

Download the latest released version (i.e., the jar file) of AB4 from its upstream repo and play around with it to familiarize with its current features.

- [ ] Decide project direction, target user profile, and problem addressed

Use your first project meeting to discuss with your team members and decide your project direction, target user profile, and the value proposition of the product, as described in [Admin  Project Scope]

**Comment by JonathanLeeWH** [comment]
## Project Direction: Morph or Optimise Addressbook level 4

As of 3 February 2019 9.30pm, based on our poll results on whether to morph or optimise the addressbook:

![image](https://user-images.githubusercontent.com/46712102/52177451-cb253a80-27fb-11e9-9580-98ad93327b52.png)

4 have voted out of 5 members.

1 vote for Morph
3 votes for Optimise

**Comment by JonathanLeeWH** [comment]
As of 3 February 10pm, based on our poll results on whether to morph or optimise the addressbook:

![image](https://user-images.githubusercontent.com/46712102/52177676-91eec980-27ff-11e9-931e-d9662baea7df.png)

5 have voted out of 5 members:

2 votes for Morph
3 votes for Optimise

So do we based on the majority and do optimise?

**Comment by jtankw3** [comment]
# Project Direction Discussion (4 Feb 2019)

Due to the close voting between morph and optimize directions, the team decided the have a meeting to brainstorm possible ideas for both directions (list of ideas below). A rough conception of project direction, target user and value proposition was decided upon. 

Project direction: Medical Inventory Management Application
Target user profile: Pharmacist 
Value proposition of the product: Streamline inventory management by providing a clear and organized overview of vital inventory information.

### To Do:

- Improve conceptualization by generating user stories and use cases (under week 4's task)
- Each member to think about individually before brainstorm session to be done online (7 Feb 2019)

### List of ideas:

**Optimise**
Idea 1: Addressbook for social workers

- Contain details of client
- Follow up date and reminder (have to contact clients once every 6 weeks)

Idea 2: Addressbook for customer service (high volume with task)

- Contain details of client
- Contain query and task for each client
- Projected completion date with reminder
- Archive completed cases for future reference 

Idea 3: Addressbook for fitness trainer

- Contain details of client (contact details, progress, goals)
- Contain exercise and diet plan for each client
- Easily customize plans depending on client progress
- Calendar for rescheduling clients 

Idea 4: Addressbook additional features (HR)

- Map view of address (integrate Google Maps API)
- Export as CSV

**Morphing**
Idea 1: Instant messaging

- Concern: Real time (though can be just a fake textbox)


Idea 2: Calendar

Idea 3: Simple Medicine Reminder (Personal)

- Timer to eat next medicine
- Scan bottle of medicine with its barcode and all its medicine information will be inside the application 
- (Low priority as project constraint is for user that prefers typing)

Idea 4: Personal debt collection book (Personal)

Idea 5: Medicine tracking (Enhanced of simple medicine reminder) [Pharmacist or Clinic Counter]

- Track medicine expiry date notify when expire or expiring batches
- Something like stock taking in Supermarkets

Idea 6: Personal income tax tracker or expenses tracker (Personal)

Idea 7: Team based task list
- Calendar of every member of the team 
- Function to find common free time
- Function to add task and invite ppl to task 

Idea 8: Keyboard shortcut filled tasklist
- Shortcut for navigating task (tab)
- Shortcut for postponing task (ctrl + p)
- Shortcut for changing priority task (ctrl + shift + p)
- Etc.

Idea 9: Anonymous feedback channel
- Client accounts for feedback
- Owner account for vetting feedback
- Categorize feedback and rating
- Owner can save relevant feedback
- Owner can turn feedback into actionable task 

Idea 10: keyboard shortcut filled notebook
- Shortcut for formatting 
- Tags for categorizing (example Tag: CS2103T for all lecture notes)
- Potentially optimize for meetings taking
