### ISSUE TITLE
[Week 4] Project Milestone: mid-v1.0

### ISSUE THREAD

**Issue by JonathanLeeWH** [cs2103-ay1819s2-t12-3/main#3]
## Description
Refer to module website

- [ ] At this point we would like to ensure that you are able to create branch-based PRs without accidentally mixing commits between PRs (a common mistake) Therefore, we strongly encourage you to complete W3.3 (in particular, W3.3c) before attempting other exercises.

- [ ] You are advised to set a time and meet with your team to complete the tasks for mid-v1.0 and start working towards completing the first draft of the user guide.

- [x] Brainstorm on user stories and use cases.

**Comment by JonathanLeeWH** [comment]
I think I will this will be the last to do for project I will post on issue tracker as usually we can just check based on the module website and I do not have the time to keep posting and updating it but I only do so for the Week 3 and Week 4 as those are the foundations for our project. So please take note of this issue and #2 as we need to settle these issue especially #2 by end of this week as that is the main foundation of our project.

**Comment by flxffy** [comment]
We brainstormed over user stories and user cases, and they have been added to "User Stories" under the "Projects" tab. Here's the link to the [user stories](https://github.com/cs2103-ay1819s2-t12-3/main/projects/1).

**Comment by JonathanLeeWH** [comment]
After our group discussion, these are the uses cases, non functional requirements and glossary we have brainstorm and draft:

## Use Cases

System: MediTabs
Actor: Pharmacist
Use Case: UC1 - View complete medicine inventory 
MSS:
1. Upon start up, System displays the complete medicine inventory.
2. Pharmacist navigates the list with arrow keys.
3. Use case ends

Extension:

1. Pharmacist used a filter function, selected inventory is shown.
	1.1 Pharmacist requests for complete inventory to be listed.
        1.2 System displays complete inventory.
	1.3 Use case resumes at step 2

System: MediTabs
Actor: Pharmacist
Use Case: UC2 - Update quantity of medicine by batches.
MSS:
1. Pharmacist takes note of index of the selected medicine in the list.
2. Pharmacist request to add new batch to medicine using the index.
3. System requests details of the new batch of medicine
4. Pharmacist enters the required details
5. System displays updated details
6. Use Case ends

Extension:
1. User cannot find manually medicine from list
	1.1 User searches for medicine with search function
	1.2 System list the search results.
	1.3 Pharmacist takes note of index of medicine in search results.
	Use case resumes at step 2

2. Medicine is new and is not in inventory
	2.1 Pharmacist request new entry to list
	2.2 Pharmacist enters details of new medicine
	2.3 Pharmacist takes note of index of medine on list
	Use case resumes at step 2

System: MediTabs
Actor: Pharmacist
Use Case: UC3 - Remove a type of medicine from the list
MSS:
1. Pharmacist request to delete entry in list
2. System displays updated list
3. Use case end
Extension:
1. Entry selected still has remaining stock, deletion not allowed
	1.1. System displays error message.
	1.2 Pharmacist request to decrease quantity of medicine to zero
	1.3 System displays updated quantity
	1.4 Repeat step 1
	Use case resumes at step 2

## Non-functional requirements:

User constraints: 
The product should be mainly focus on catering towards users with higher preference towards typing commands rather than using other forms of interaction such as mouse. GUI interaction is allowed though main focus should be on command line interface inputs.
The product should only be for a single user, in other words, any features for example switching of profiles for different users which involves multi user support should be avoided.

Data requirements: 
The data that is stored locally should be editable by user. In other words, expert users can open the file without using the application and edit it for his or her liking.
The use of MySQL database management systems or similar database management systems are not allowed.

Environment requirements:
The product should work on all platforms mainly Windows, Linux and MacOS platforms.
The product should not connect to any personal remote server though connecting of reliable public APIs like Google API are allowed but fallback system should be implemented such as a backup if connection to public APIs does not work during test.

Portability requirements:
The software should not require any installer, in other words, should be able to run without installing any additional softwares. In this case, we have to use .jar when releasing the product.

Testability requirements:
Avoid implementing features that are hard to test both manual and automated testing. In other words, avoid depending heavily on remote APIs as they may not work and usually out of our control.
No audio related features due to project constraints. Possibly avoid features that uses sounds as indicators.

Notes about project scope: 

The target user should be very specific. In this case, we have decided on Pharmacists who usually in charge of medicine inventory/stock taking.

Optimised the product to suit the target user in this case Pharmacists in charge of medicine inventory and stock taking. In other words, add features that are applicable to them or unique to them and attractive to them. As the product will be graded on its ability to meet the needs of the target user (Pharmacist in charge of medicine inventory or stock taking) and the features should complement each other.

## Glossary
Inventory - a complete listing of merchandise and stock currently in possession.
Batches - a quantity of goods at one time

**Comment by JonathanLeeWH** [comment]
@jtankw3 @flxffy I will be closing this issue since we have completed the tasks for this issue. Thank you.
